// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cGroupBy
List cGroupBy(List input, String group_on, IntegerVector tube_nums);
RcppExport SEXP _flowProc_cGroupBy(SEXP inputSEXP, SEXP group_onSEXP, SEXP tube_numsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< String >::type group_on(group_onSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tube_nums(tube_numsSEXP);
    rcpp_result_gen = Rcpp::wrap(cGroupBy(input, group_on, tube_nums));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flowProc_cGroupBy", (DL_FUNC) &_flowProc_cGroupBy, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_flowProc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
