#' Get file structure information from a given directory, using the lower directories as groupings.
#'
#' @param path Top directory which contains the lower directories serving as different groups.
#' @param ext File extension of files to be included. Generally this will be either lmd or fcs (case sensitive)
#' @return Matrix containing filepath, group, label (regex currently hardcoded for specific naming schemata)
#' @examples
#' get_dir('/data/flowData', 'FCS')
#' get_dir('../data/fcs', 'lmd')
get_dir <- function(path, ext) {
	l = lapply(list.dirs(path, full.names=FALSE, recursive=FALSE), function(i) {
		filelist = list.files(file.path(path, i), pattern=ext, full.names=FALSE)
		f = sapply(filelist, function(x) {
				   r = regexec('^([KMPB\\d-]+) CLL 9F (\\d+).*.LMD$', x, perl=TRUE)
				   if ('-1' %in% r)
				   	   return(c(NA, NA, NA, NA))
				   m = regmatches(x, r)
				   return(c(file.path(path, i, x), i, m[[1]][[2]], strtoi(m[[1]][[3]])))
  		})
  		f = t(f)
  		f = f[!is.na(f[,1]),]
  		colnames(f) = c('filepath', 'group', 'label', 'set')
  		return(f)
  		})
  	files = do.call(rbind, l)
  	return(files)
}

read_file <- function(file_row) {
	f = read.FCS(as.character(file_row[['filepath']]), dataset=1)
	# use simplified markernames, this might be an inappropriate simplification
	m = strsplit(markernames(f), '-')
	newn = sapply(m, function(x) { x[[1]] } )
	colnames(f) = newn

	return (c(file_row, fcs=f))
}

#' Load fcs files into a file matrix
#'
#' @param file_matrix Matrix containing filename, group, id and set information as generated by get_dir().
#' @return File matrix with loaded fcs files.
#' @examples
#' file_matrix = get_dir('/data', 'fcs')
#' read_files(file_matrix)
read_files <- function(file_matrix) {
	# Load fcs files into file matrix
	#
	# Args:
	# 	file_matrix: matrix containing filename, group, id, and set information
	# 	path: path of top directory used in grouping
	#
	# Returns:
	# 	file_matrix ẃith flowframe column with loaded fcs files
	fcs_list = mclapply(file_list[,'filepath'], function(x) {
						  f = read.FCS(as.character(x), dataset=1)
						  m = strsplit(markernames(f), '-')
						  # use simplified markernames that actually describe biological properties
						  newn = sapply(m, function(x) { x[[1]] } )
						  colnames(f) = newn
						  return(f)
		}, mc.cores=CPUNUM)

	return (cbind(file_list, fcs=fcs_list))
}
