# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Group list of S4 flow entries by slot and optionally limit to tube
#'
#' Disable tube limiting by passing an empty vector such as vector().
#'
#' @param input List of flow entries.
#' @param group_on String for slot to group on.
#' @param tube_nums Integer vector for tube numbers to be used.
#' @export
cGroupBy <- function(input, group_on, tube_nums) {
    .Call(`_flowProc_cGroupBy`, input, group_on, tube_nums)
}

#' @export
cppGetDir <- function(dir_path, dataset) {
    .Call(`_flowProc_cppGetDir`, dir_path, dataset)
}

